engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
    exclude_fingerprints:
        - 663482e3eb0f04e975ea82ea921cdaf4
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**/*
  - "**.js"
exclude_paths:
    - bower_components/
    - tests/**/*.spec.js
    - src/**/*.conf.js
    - e2e-tests/*.js
    - gulpfile.js